NSABP_POC/Controllers/UserLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NSABP_Model_BO_;
using NSABP_BLL;
using System.Data;


namespace NSABP_Product.Controllers
{
    public class UserLoginController : Controller
    {
        // GET: UserLogin



        public ActionResult LoginPage(string UserName, String PWD)
        {

            LoginBO loginBO = new LoginBO();
            if (UserName != null && PWD != null)
            {
                loginBO.UserName = UserName;
                loginBO.Password = PWD;
                DataTable dt_UserDetails = new DataTable();
                dt_UserDetails = LoginBLL.getuserDetails(loginBO);
                if (dt_UserDetails.Rows.Count > 0)
                {
                    //Session["Protocol_Id"] = dt_UserDetails.Rows[0]["Protocol_Id"].ToString();
                    //Session["Role_Id"] = dt_UserDetails.Rows[0]["Role_Id"].ToString();
                    Session["User_ID"] = dt_UserDetails.Rows[0]["User_ID"].ToString();
                    Session["UserName"] = dt_UserDetails.Rows[0]["UserName"].ToString();
                    Session["FName"] = dt_UserDetails.Rows[0]["FName"].ToString();
                    Session["LName"] = dt_UserDetails.Rows[0]["LName"].ToString();
                    //Session["UserDetails"] = dt_UserDetails;
                    Session["PhoneNumber"] = dt_UserDetails.Rows[0]["PhoneNumber"].ToString();
                    Session["email"] = dt_UserDetails.Rows[0]["email"].ToString();
                    /////////////////////////////////////
                    //Session["Protocol_List"] = Base_BLL.List_Protocols(Convert.ToInt32(dt_UserDetails.Rows[0]["User_ID"]));
                    List<Protocol_role_site> List_Protocol_role_site = User_BLL.ListProtocol_role_site(Convert.ToInt16(Session["User_ID"]));
                    Session["Role_Name"] = List_Protocol_role_site[0].Role_Name;
                    Session["Protocol_Code"] = List_Protocol_role_site[0].Protocol_Code;
                    Session["Protocol_Id"] = List_Protocol_role_site[0].ProtocolID;
                    Session["Protocol_List"] = List_Protocol_role_site;
                    if (List_Protocol_role_site[0].T8_sites_Id != null)
                        Session["Site"] = List_Protocol_role_site[0].T8_sites_Id;
                    if (Session["Role_Name"].ToString() == "SuperAdmin")
                        return RedirectToAction("GetUserDetails", "User");
                    else if (Session["Role_Name"].ToString() == "DIT")
                        return RedirectToAction("FormEntry", "FormEntry");
                    else
                    {
                        List<Forms> List_Forms = Base_BLL.Listforms(Convert.ToInt16(Session["Protocol_Id"]));
                        Session["Forms_List"] = List_Forms;
                        return RedirectToAction(List_Forms[0].URL.Split('/')[2], List_Forms[0].URL.Split('/')[1]);
                    }

                }
                ViewBag.Message = "Login Failed";
                return View();
            }
            else
            {
                return View();
            }
        }
        public ActionResult LogOut()
        {
            Session.Clear();
            Session.Abandon();
            return View("LoginPage");

        }

        public ActionResult Forms_Load(int protocolID)
        {
            List<Protocol_role_site> List_Protocol_role_site = User_BLL.ListProtocol_role_site(Convert.ToInt16(Session["User_ID"]));

            List_Protocol_role_site = List_Protocol_role_site.Where(x => x.ProtocolID == protocolID).ToList();
            Session["Role_Name"] = List_Protocol_role_site[0].Role_Name;
            Session["Protocol_Code"] = List_Protocol_role_site[0].Protocol_Code;
            Session["Protocol_Id"] = List_Protocol_role_site[0].ProtocolID;
            //Session["Protocol_List"] = List_Protocol_role_site;
            if (List_Protocol_role_site[0].T8_sites_Id != null)
                Session["Site"] = List_Protocol_role_site[0].T8_sites_Id;


            if (Session["Role_Name"].ToString() == "SuperAdmin")
                return RedirectToAction("GetUserDetails", "User");
            else if (Session["Role_Name"].ToString() == "DIT")
                return RedirectToAction("FormEntry", "FormEntry");
            else
            {
                List<Forms> List_Forms = Base_BLL.Listforms(Convert.ToInt16(Session["Protocol_Id"]));
                Session["Forms_List"] = List_Forms;
                return RedirectToAction(List_Forms[0].URL.Split('/')[2], List_Forms[0].URL.Split('/')[1]);
            }

        }



        public ActionResult ERRORPAGE()
        {
            return View();
        }


        public ActionResult ChangePassword()
        {
            return View();
        }
        public ActionResult ChangePassword(string password)
        {
            if(User_BLL.Changepwd(password,Convert.ToInt16(Session["User_ID"])))
            {

            }
            return View();
        }
    }
}

NSABP_POC/Views/UserLogin/ChangePassword.cshtml
<div is="ChangePWD">
    <section id="wrapper">
        <div class="card">
            <div class="card-body">
                <h3 class="text-center m-b-20">Change Password</h3>

                <div class="form-group ">
                    <div class="col-xs-12">
                        <input class="form-control" type="password" required="" name="NewPassword1" placeholder="New Password">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-xs-12">
                        <input class="form-control" type="password" data-validation-match-match="NewPassword1" required="" name="NewPassword2" placeholder="COnfirm Password">
                    </div>
                </div>

                <div class="form-group text-center">
                    <div class="col-xs-12 p-b-20">
                        <button class="btn btn-block btn-lg btn-info btn-rounded" type="button">Change Password</button>
                    </div>

                </div>


            </div>
        </div>
    </section>
</div>

NSABP_POC/Views/UserLogin/ERRORPAGE.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="../assets/images/favicon.png">
    <title>NSABP</title>

    <!-- Custom CSS -->
    <link href="~/dist/css/style.min.css" rel="stylesheet">
    <!-- page css -->
    <link href="~/dist/css/pages/error-pages.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body class="skin-megna fixed-layout">
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <section id="wrapper" class="error-page">
        <div class="error-box">
            <div class="error-body text-center">
                <h1>400</h1>
                <h3 class="text-uppercase">Page Not Found !</h3>
                <p class="text-muted m-t-30 m-b-30">YOU SEEM TO BE TRYING TO FIND HIS WAY HOME</p>

                <a href="~/UserLogin/LoginPage" class="btn btn-info btn-rounded waves-effect waves-light m-b-40">Back to Login Page</a>
            </div>

        </div>
    </section>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="~/assets/node_modules/jquery/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="~/assets/node_modules/popper/popper.min.js"></script>
    <script src="~/assets/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <!--Wave Effects -->
    <script src="~/dist/js/waves.js"></script>
</body>

</html>

NSABP_POC/Views/UserLogin/LoginPage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/images/favicon.png">

    <title>User Login</title>
    @*<link href="dist/css/pages/login-register-lock.css" rel="stylesheet">*@
    <link href="~/dist/css/pages/login-register-lock.css" rel="stylesheet" />
    <link href="~/dist/css/style.min.css" rel="stylesheet">

</head>
<body class="skin-default card-no-border">
    <div class="preloader">
        <div class="loader">
            <div class="loader__figure"></div>
            <p class="loader__label">User Login</p>
        </div>
    </div>

    <section id="wrapper">
        @*style="background-image:url(~/assets/images/background/login-register.jpg);"*@
        <div class="login-register">
            <div class="login-box card">
                @{
                    if (ViewBag.Message != null)
                    {
                        if (ViewBag.Message.Contains("Fail"))
                        {
                            <div class="alert alert-danger alert-dismissible col-md-12" id="myAlert">
                                <a href="#" class="close">&times;</a>
                                <strong>@ViewBag.Message</strong>
                            </div>
                        }


                    }
                }
                <div class="card-body">
                    <h3 class="text-center m-b-20">Sign In</h3>

                    @*<form class="form-horizontal form-material" action="LoginPage">*@
                    @using (Html.BeginForm("LoginPage", "UserLogin", FormMethod.Post))
                    {

                        <div class="form-group ">
                            <div class="col-xs-12">
                                <input class="form-control" type="text" required="" name="UserName" placeholder="Username">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-12">
                                <input class="form-control" type="password" required="" name="PWD" placeholder="Password">
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-12">
                                <div class="d-flex no-block align-items-center">
                                    <div class="ml-auto">
                                        <a href="javascript:void(0)" id="to-recover" class="text-muted"><i class="fas fa-lock m-r-5"></i> Forgot pwd?</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group text-center">
                            <div class="col-xs-12 p-b-20">
                                <button class="btn btn-block btn-lg btn-info btn-rounded" type="submit">Log In</button>
                            </div>
                        </div>
                    }
                    @*</form>*@
                </div>
            </div>
        </div>
    </section>

    <script src="~/assets/node_modules/jquery/jquery-3.2.1.min.js"></script>
    <script src="~/assets/node_modules/popper/popper.min.js"></script>
    <script src="~/assets/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>

    <script type="text/javascript">
        $(function () {
            $(".preloader").fadeOut();
        });
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        });
        $('#to-recover').on("click", function () {
            $("#loginform").slideUp();
            $("#recoverform").fadeIn();
        });
    </script>
    <script>
        $(document).ready(function () {
            $(".close").click(function () {
                $("#myAlert").alert("close");
            });
            $('#btnlogin').click(function () {
                //var data = JSON.stringify($("#testform").serialize())  ;
                //if ($('#txtusername').val() == '') {
                //    alert('Please enter User name.');
                //    return false;
                //}
                //if ($('#txtpwd').val() == '') {
                //    alert('Please enter password.');
                //    return false;
                //}
                debugger;
                $.post("/UserLogin/LoginPage", { Username: "", PWD: "" }, function (data) {
                    alert(data.status);
                });
            });
        });
       
    </script>

</body>
</html>